package utils;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class PropertiesGenerator {
	
	private String fileName;
	
	public PropertiesGenerator(String file){
	this.fileName=file;	
	}

	
	public void write() throws IOException{
		
		
	    FileWriter fstream = new FileWriter(fileName);
        BufferedWriter out = new BufferedWriter(fstream);
    out.write("#archivo de configuracion generado automaticamente - Config file generated by default"
	+"\n" 
    +"#######################\n" 
    +"# PATH\n" 
    +"#######################\n" 
    +"path.source=c:/data/\n" 
    +"path.target=c:/iabinmaps/\n" 
    +"\n" 
    +"bioclim.path=bioclim/\n" 
    +"threat.path=threat/\n" 
    +"species.path=species/\n" 
    +"summaries.path=summaries/\n" 
    +"summaries.kmloutputpath=protectedArea/\n" 
    +"\n" 
    +"#######################\n" 
    +"# RASTERS\n" 
    +"#######################\n" 
    +"rasters=P1;P2\n" 
    +"P1.group=bioclim\n" 
    +"P1.filename=P1.asc\n" 
    +"P1.descripcion=Annual mean temperature ºC\n" 
    +"P2.group=bioclim\n" 
    +"P2.filename=P2.asc\n" 
    +"P2.descripcion=Mean diurnal temperature range ºC\n" 
    +"#######################\n" 
    +"# SHAPEFILES\n" 
    +"#######################\n" 
    +"shapes=PA\n" 
    +"PA.group=summaries\n" 
    +"PA.shapefile=SurAmerica.shp\n" 
    +"\n" 
    +"#######################\n" 
    +"# ZOOM\n" 
    +"#######################\n" 
    +"zoom.min=0\n" 
    +"zoom.max=1\n" 
    +"\n" 
    +"#######################\n" 
    +"# KML\n" 
	+"#######################\n" 
	+"\n" 
	+"style.url=http://wikipedia.agilityhoster.com/estilo.kml#estilo\n" 
	+"\n" 
	+"#######################\n" 
	+"# PROTECTED AREA\n" 
	+"#######################\n" 
	+"PA.server.url=http://wikipedia.agilityhoster.com/\n" 
	+"PA.shape.column.indexes=2;4;5;20\n" 
	+"PA.shape.column.names=Name;Country;State;UNCAT\n" 
	+"PA.kml.main=mainKML.kml\n" 
	+"\n" 
	+"#######################\n" 
	+"# COLORS\n" 
	+"#######################\n" 
	+"P1.color.type=temperature\n" 
	+"P2.color.type=precipitation\n" 
	+"\n" 
	+"temperature.color.min= 255;255;0\n" 
	+"temperature.color.max= 255;0;0\n" 
	+"\n" 
	+"temperature.scale=quantiles\n" 
	+"temperature.scale.quantiles=5\n" 
	+"\n" 
	+"precipitation.color.min= 255;255;255\n" 
	+"precipitation.color.max= 0;0;255\n" 
	+"\n" 
	+"precipitation.scale=continuous\n" );
	out.close();
	
	}


	
	
	
}
