package utils;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class PropertiesGenerator {
	
	private String fileName;
	
	public PropertiesGenerator(String file){
	this.fileName=file;	
	}

	
	public void write() throws IOException{
		
		
	    FileWriter fstream = new FileWriter(fileName);
        BufferedWriter out = new BufferedWriter(fstream);
    out.write("#archivo de configuracion generado automaticamente - Config file generated by default");
    out.write("\n");
    out.write("#######################\n");
    out.write("# PATH\n");
    out.write("#######################\n");
    out.write("path.source=c:/data/\n");
    out.write("path.target=c:/iabinmaps/\n");
    out.write("\n");
    out.write("bioclim.path=bioclim/\n");
    out.write("threat.path=threat/\n");
    out.write("species.path=species/\n");
    out.write("summaries.path=summaries/\n");
    out.write("summaries.kmloutputpath=protectedArea/\n");
    out.write("\n");
    out.write("#######################\n");
    out.write("# RASTERS\n");
    out.write("#######################\n");
    out.write("rasters=P1;P2\n");
    out.write("P1.group=bioclim\n");
    out.write("P1.filename=P1.asc\n");
    out.write("P1.descripcion=Annual mean temperature ºC\n");
    out.write("P2.group=bioclim\n");
    out.write("P2.filename=P2.asc\n");
    out.write("P2.descripcion=Mean diurnal temperature range ºC\n");
    out.write("#######################\n");
    out.write("# SHAPEFILES\n");
    out.write("#######################\n");
    out.write("shapes=PA\n");
    out.write("PA.group=summaries\n");
    out.write("PA.shapefile=SurAmerica.shp\n");
    out.write("\n");
    out.write("#######################\n");
    out.write("# ZOOM\n");
    out.write("#######################\n");
    out.write("zoom.min=0\n");
    out.write("zoom.max=1\n");
    out.write("\n");
    out.write("#######################\n");
    out.write("# KML\n");
	out.write("#######################\n");
	out.write("\n");
	out.write("style.url=http://wikipedia.agilityhoster.com/estilo.kml#estilo\n");
	out.write("\n");
	out.write("#######################\n");
	out.write("# PROTECTED AREA\n");
	out.write("#######################\n");
	out.write("PA.server.url=http://wikipedia.agilityhoster.com/\n");
	out.write("PA.shape.column.indexes=2;4;5;20\n");
	out.write("PA.shape.column.names=Name;Country;State;UNCAT\n");
	out.write("PA.kml.main=mainKML.kml\n");
	out.write("\n");
	out.write("#######################\n");
	out.write("# COLORS\n");
	out.write("#######################\n");
	out.write("P1.color.type=temperature\n");
	out.write("P2.color.type=precipitation\n");
	out.write("\n");
	out.write("temperature.color.min= 255;255;0\n");
	out.write("temperature.color.max= 255;0;0\n");
	out.write("\n");
	out.write("temperature.scale=quantiles\n");
	out.write("temperature.scale.quantiles=5\n");
	out.write("\n");
	out.write("precipitation.color.min= 255;255;255\n");
	out.write("precipitation.color.max= 0;0;255\n");
	out.write("\n");
	out.write("precipitation.scale=continuous\n");
	out.close();
	
	}


	
	
	
}
